-- CreateTable
CREATE TABLE "employment_contracts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "kontrakid" INTEGER NOT NULL,
    "nomorkontrak" TEXT NOT NULL,
    "judulkontrak" TEXT NOT NULL,
    "tanggalmulai" DATETIME NOT NULL,
    "tanggalakhir" DATETIME NOT NULL,
    "namaperusahaan" TEXT NOT NULL,
    "namadirektwr" TEXT NOT NULL,
    "alamatperusahaan" TEXT NOT NULL,
    "notelpperusahaan" TEXT NOT NULL,
    "emailperusahaan" TEXT NOT NULL,
    "npwpperusahaan" TEXT NOT NULL,
    "namalengkappegawai" TEXT NOT NULL,
    "jabatan" TEXT NOT NULL,
    "alamatpegawai" TEXT NOT NULL,
    "jeniskelamin" TEXT NOT NULL,
    "usia" INTEGER NOT NULL,
    "jenispegawai" TEXT NOT NULL,
    "noktp" TEXT NOT NULL,
    "notelppegawai" TEXT NOT NULL,
    "emailpegawai" TEXT NOT NULL,
    "jobdesc" TEXT NOT NULL,
    "tempatkerja" TEXT NOT NULL,
    "waktukerja" TEXT NOT NULL,
    "waktuistirahat" TEXT NOT NULL,
    "ketentuancuti" TEXT NOT NULL,
    "ketentulembur" TEXT NOT NULL,
    "gajipokok" BIGINT NOT NULL,
    "tunjangantetap" BIGINT NOT NULL,
    "tunjangantidaktetap" BIGINT NOT NULL,
    "jaminansosial" TEXT NOT NULL,
    "fasilitaslain" TEXT NOT NULL,
    "perlindunganhukum" TEXT NOT NULL,
    "kerahasiaan" TEXT NOT NULL,
    "ketentuandisiplin" TEXT NOT NULL,
    "sanksi" TEXT NOT NULL,
    "pelanggaran" TEXT NOT NULL,
    "pemutusanhubungan" TEXT NOT NULL,
    CONSTRAINT "employment_contracts_kontrakid_fkey" FOREIGN KEY ("kontrakid") REFERENCES "contracts" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "employment_contracts_kontrakid_key" ON "employment_contracts"("kontrakid");
