import type { Metadata } from "next";
import { Poppins, Noto_Sans } from "next/font/google";
// import { Navbar } from "@/components/custom/navbar";
// import { Footer } from "@/components/custom/footer";
import "./globals.css";
import { ToastProvider } from "../components/ui/toast";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${notoSans.variable} font-sans antialiased`}>
        <ToastProvider>
          {/* <Navbar /> */}
          {children}
          {/* Footer will be handled by individual layout groups (public)/(main) */}
        </ToastProvider>
      </body>
    </html>
  );
}
