interface OpenRouterConfig {
  apiKey: string;
  baseUrl: string;
  model: string;
  siteName: string;
  siteUrl: string;
}

interface AIMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

interface AIResponse {
  success: boolean;
  content?: string;
  error?: string;
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
    total_cost?: number;
  };
}

interface ContractDetails {
  id: number;
  name: string;
  counterparty: string;
  expirationDate: Date;
  daysUntilExpiry: number;
  contractType: string;
  status: string;
}

export class AIService {
  private config: OpenRouterConfig;

  constructor() {
    this.config = {
      apiKey: process.env.OPENROUTER_API_KEY || '',
      baseUrl: 'https://openrouter.ai/api/v1',
      model: process.env.AI_MODEL || 'anthropic/claude-3.5-sonnet',
      siteName: 'IContract AI Assistant',
      siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
    };

    if (!this.config.apiKey) {
      console.warn('⚠️ OPENROUTER_API_KEY environment variable is not set');
    }
  }

  /**
   * Generic method for making AI requests to OpenRouter
   */
  private async makeRequest(
    messages: AIMessage[], 
    options?: {
      temperature?: number;
      maxTokens?: number;
      systemPrompt?: string;
    }
  ): Promise<AIResponse> {
    try {
      if (!this.config.apiKey) {
        throw new Error('OpenRouter API key is not configured');
      }

      // Add system prompt if provided
      const requestMessages: AIMessage[] = options?.systemPrompt 
        ? [{ role: 'system', content: options.systemPrompt }, ...messages]
        : messages;

      console.log('🤖 Making AI request to OpenRouter...');
      console.log(`📝 Model: ${this.config.model}`);
      console.log(`💬 Messages: ${requestMessages.length}`);

      const response = await fetch(`${this.config.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.config.apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': this.config.siteUrl,
          'X-Title': this.config.siteName
        },
        body: JSON.stringify({
          model: this.config.model,
          messages: requestMessages,
          temperature: options?.temperature || 0.7,
          max_tokens: options?.maxTokens || 2000,
          stream: false
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`❌ OpenRouter API error: ${response.status}`, errorText);
        throw new Error(`OpenRouter API error: ${response.status} - ${errorText}`);
      }

      const data = await response.json();
      
      if (!data.choices || data.choices.length === 0) {
        throw new Error('No response generated by AI model');
      }

      const content = data.choices[0]?.message?.content;
      if (!content) {
        throw new Error('Empty response from AI model');
      }

      console.log('✅ AI response received');
      console.log(`📊 Usage: ${data.usage?.total_tokens || 'unknown'} tokens`);

      return {
        success: true,
        content: content.trim(),
        usage: data.usage
      };

    } catch (error) {
      console.error('❌ AI Service Error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown AI service error'
      };
    }
  }

    /**
     * Review a contract and provide legal analysis
     */
    async reviewContract(contractContent: string, contractType: string = 'general'): Promise<AIResponse> {
    const systemPrompt = `You are an expert legal analyst specializing in Indonesian contract law and business practices.

    IMPORTANT: Structure your response using EXACTLY these section headers with ## formatting:

    ## Executive Summary
    [Provide 2-3 sentences overview]

    ## Critical Issues and Risks
    [List all high-risk problems, legal violations, and critical missing elements that could cause legal or financial harm]

    ## Recommendations for Improvement
    [Provide specific, actionable suggestions to enhance the contract]

    ## Positive Elements
    [Highlight well-drafted clauses and compliant elements]

    ## Key Terms Analysis
    [Analyze main obligations, rights, and conditions]

    ## Indonesian Law Compliance
    [Check against Indonesian legal requirements - UU, PP, Permendag, etc.]

    ## Missing Standard Clauses
    [Identify standard clauses that should be included]

    ## Overall Assessment
    [Provide 1-10 rating with clear justification]

    Each section should:
    - Be clearly separated with ## headers
    - Use bullet points for lists
    - Be specific and actionable
    - Focus on Indonesian legal standards
    - Provide clear business guidance

    Keep each section focused and avoid mixing different types of content.`;

    const userMessage = `Please review this ${contractType} contract and provide a structured legal analysis:

    **Contract Type:** ${contractType}
    **Document Content:**
    ${contractContent}

    Provide a comprehensive legal analysis following the exact section structure specified, focusing on Indonesian law and business best practices.`;

    return this.makeRequest([
        { role: 'user', content: userMessage }
    ], {
        systemPrompt,
        temperature: 0.3, // Lower temperature for consistent legal analysis
        maxTokens: 4000
    });
    }

  /**
   * Generate contract drafting assistance
   */
  async assistContractDrafting(contractType: string, requirements: string): Promise<AIResponse> {
    const systemPrompt = `You are a professional contract drafting assistant specializing in Indonesian business law.

Create comprehensive contract guidance including:

1. **Essential Clauses** (must-have provisions for this contract type)
2. **Contract Structure** (recommended organization and flow)
3. **Key Terms to Define** (important definitions and terminology)
4. **Negotiation Points** (areas that typically require discussion)
5. **Risk Mitigation Clauses** (protection mechanisms)
6. **Indonesian Law Compliance** (specific legal requirements)
7. **Sample Language** (example clauses where helpful)

Focus on Indonesian legal standards and business practices. Make recommendations practical and implementable.`;

    const userMessage = `I need help drafting a ${contractType} contract with these requirements:

**Contract Type:** ${contractType}
**Specific Requirements:**
${requirements}

Please provide comprehensive drafting guidance that complies with Indonesian law and protects both parties' interests.`;

    return this.makeRequest([
      { role: 'user', content: userMessage }
    ], {
      systemPrompt,
      temperature: 0.5,
      maxTokens: 4000
    });
  }

  /**
   * Generate expiration/validity notifications
   */
  async generateExpirationNotification(contractDetails: ContractDetails): Promise<AIResponse> {
    const systemPrompt = `You are a professional contract management assistant. Generate clear, actionable contract expiration notifications for different stakeholders.

Create notifications that are:
- Professional and clear
- Action-oriented with specific next steps
- Appropriate for business communication
- Include relevant deadline information
- Suggest appropriate actions based on urgency

Format responses in clean, professional language suitable for business communications.`;

    const urgencyLevel = contractDetails.daysUntilExpiry <= 30 ? 'URGENT' : 
                        contractDetails.daysUntilExpiry <= 90 ? 'HIGH PRIORITY' : 'NOTICE';

    const userMessage = `Generate contract expiration notifications with these details:

**Contract Information:**
- Contract Name: ${contractDetails.name}
- Counterparty: ${contractDetails.counterparty}
- Expiration Date: ${contractDetails.expirationDate.toLocaleDateString('id-ID')}
- Days Until Expiry: ${contractDetails.daysUntilExpiry}
- Contract Type: ${contractDetails.contractType}
- Current Status: ${contractDetails.status}
- Urgency Level: ${urgencyLevel}

Please create:
1. **Email Notification** (for legal/management team)
2. **Dashboard Alert** (brief message for system display)
3. **Action Items** (specific next steps required)
4. **Timeline Recommendations** (when to take each action)`;

    return this.makeRequest([
      { role: 'user', content: userMessage }
    ], {
      systemPrompt,
      temperature: 0.4,
      maxTokens: 2000
    });
  }

  /**
   * Suggest specific contract clauses
   */
  async suggestClauses(contractType: string, specificNeeds: string[]): Promise<AIResponse> {
    const systemPrompt = `You are a legal clause specialist with expertise in Indonesian contract law. 

Provide specific, legally sound contract clauses that:
- Comply with Indonesian legal requirements
- Are enforceable and practical
- Protect both parties appropriately
- Use clear, professional language
- Include necessary legal terminology

For each clause, provide:
- The clause text in both English and Bahasa Indonesia (where applicable)
- Legal justification
- Implementation notes
- Alternative versions if relevant`;

    const userMessage = `For a ${contractType} contract, I need clauses addressing:

**Contract Type:** ${contractType}
**Specific Needs:**
${specificNeeds.map(need => `- ${need}`).join('\n')}

Please provide specific, legally compliant clause suggestions for each need, with explanations of why each clause is important and how it protects the parties involved.`;

    return this.makeRequest([
      { role: 'user', content: userMessage }
    ], {
      systemPrompt,
      temperature: 0.6,
      maxTokens: 3000
    });
  }

  /**
   * Compare two contracts
   */
  async compareContracts(contract1: string, contract2: string, comparisonContext?: string): Promise<AIResponse> {
    const systemPrompt = `You are a contract comparison specialist. Analyze two contracts and provide a comprehensive comparison.

Your analysis should include:

1. **Key Differences Summary** (high-level overview)
2. **Term-by-Term Comparison** (specific clause differences)
3. **Risk Analysis** (which contract offers better protection)
4. **Missing Elements** (what each contract lacks)
5. **Advantages/Disadvantages** (pros and cons of each)
6. **Recommendations** (which to choose or how to improve)
7. **Indonesian Law Perspective** (compliance and enforceability)

Be objective and provide practical business guidance.`;

    const contextNote = comparisonContext ? `\n**Comparison Context:** ${comparisonContext}\n` : '';

    const userMessage = `Please compare these two contracts:${contextNote}

**CONTRACT A:**
${contract1}

**CONTRACT B:**
${contract2}

Provide a comprehensive comparison focusing on legal protection, business risk, and practical implementation under Indonesian law.`;

    return this.makeRequest([
      { role: 'user', content: userMessage }
    ], {
      systemPrompt,
      temperature: 0.3,
      maxTokens: 4000
    });
  }

  /**
   * Extract key information from contract text
   */
  async extractContractInfo(contractContent: string): Promise<AIResponse> {
    const systemPrompt = `You are a contract information extraction specialist. Extract and summarize key information from contract documents.

Extract and organize the following information in a structured format:

**Basic Information:**
- Contract parties (names, addresses, roles)
- Contract type and purpose
- Effective date and duration
- Key dates (start, end, milestones)

**Financial Terms:**
- Contract value/consideration
- Payment terms and schedule
- Penalties/late fees
- Currency and payment methods

**Key Obligations:**
- Party A responsibilities
- Party B responsibilities
- Deliverables and timelines
- Performance criteria

**Legal Terms:**
- Governing law
- Dispute resolution
- Termination conditions
- Liability limitations

**Risk Factors:**
- Identified risks
- Mitigation measures
- Compliance requirements

Format the response in clear, organized sections.`;

    const userMessage = `Extract key information from this contract:

${contractContent}

Please provide a comprehensive summary of all important contract elements in a structured format.`;

    return this.makeRequest([
      { role: 'user', content: userMessage }
    ], {
      systemPrompt,
      temperature: 0.2,
      maxTokens: 3000
    });
  }
  /**
   * Extract structured contract data from raw text
   */
  async extractContractData(contractContent: string, contractType: string): Promise<AIResponse> {
    // Different system prompts based on contract type
    let systemPrompt: string;
    
    if (contractType === 'employment') {
      systemPrompt = `You are an employment contract data extraction specialist. Extract structured information from employment/job contract documents.

  Extract and organize the following information from the provided employment contract:

  ## Contract Basics
  - Contract Number
  - Contract Title
  - Title
  - Employment Type (Employment, Freelance, Internship)
  - Start Date and Duration/End Date
  - Probation Period (if any)

  ## Company Information
  - Company Name
  - Director Name
  - Company Address (complete)
  - Company Phone Number
  - Company Email
  - Company NPWP

  ## Employee Information
  - Employee Full Name
  - Employee Position
  - Employee Address (complete)
  - Gender
  - Date of Birth/Age
  - Contract Type (PKWTT, PKWT)
  - Employee ID Number (KTP/Passport)
  - Employee Phone Number
  - Employee Email

  ## Job Details
  - Job Description and Responsibilities
  - Work Location/Office
  - Work Schedule (days, hours)
  - Break Time/Lunch Hours
  - Leave/Vacation Policy

  ## Compensation & Benefits
  - Basic Salary (monthly/yearly)
  - Fixed Allowances (transport, meal, etc.)
  - Variable Allowances (performance bonus, incentives)
  - Social Security (BPJS Kesehatan, BPJS Ketenagakerjaan)
  - Health Insurance
  - Other Benefits (laptop, phone, car, training, etc.)
  - Payment Schedule and Method

  ## Legal & Compliance
  - Confidentiality Clauses
  - Non-compete Agreements
  - Disciplinary Rules
  - Termination Conditions
  - Notice Period
  - Severance Pay
  - Dispute Resolution

  Format your response clearly with headers and bullet points. If information is not available, state "Not specified in document".

  Focus on employment-specific terms and Indonesian labor law requirements.`;

    } else {
      // Original partnership/general contract prompt
      systemPrompt = `You are a contract data extraction specialist. Extract structured information from contract documents.

  Extract and organize the following information from the provided contract text:

  ## Contract Basics
  - Contract Number
  - Contract Title
  - Contract Type (Partnership, Service, Supply, etc.)
  - Start Date and Duration
  - Contract Value/Amount

  ## Party Information
  For each party, extract:
  - Company Name
  - Director/Representative Name  
  - Complete Address
  - Phone Number
  - Email Address
  - NPWP (Tax ID)
  - Business License Number

  ## Service/Scope Details
  - Type of Service/Business
  - Detailed Service Description
  - Operating Territory/Region
  - Rights and Obligations of each party
  - Service Terms and Conditions

  ## Financial Terms
  - Contract Value/Amount
  - Payment Terms and Conditions
  - Payment Method (Bank, Account Details)
  - Payment Schedule
  - Late Payment Penalties

  ## Legal Terms
  - Claim Deadlines
  - Maximum Compensation
  - Dispute Resolution Mechanism
  - Force Majeure Clauses

  Format your response clearly with headers and bullet points. If information is not available, state "Not specified in document".

  Be thorough but concise. Focus on extracting exact values and text from the document.`;
    }

    const userMessage = `Please extract structured contract information from this ${contractType} document:

  ${contractContent}

  Provide a comprehensive extraction of all contract details in a clear, organized format suitable for ${contractType} contracts.`;

    return this.makeRequest([
      { role: 'user', content: userMessage }
    ], {
      systemPrompt,
      temperature: 0.1, // Very low temperature for consistent extraction
      maxTokens: 3000
    });
  }
}


// Export singleton instance
export const aiService = new AIService();

// Export types for use in other files
export type { AIResponse, ContractDetails };